---
abstract: 'Semantic Template wrapper for Dancer'
author:
  - 'Squeeks <squeek@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102341, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Template-Semantic
requires:
  Dancer: 1.10
  Template::Semantic: 0.06
version: 0.01
